# Shell variables
# Generated by 'wal'
wallpaper='/home/sf/wallpapers/0d3623c187d15098071f74361444ef34.jpg'

# Special
background='#0a0d1b'
foreground='#eee4c7'
cursor='#eee4c7'

# Colors
color0='#0a0d1b'
color1='#E49E71'
color2='#FEC87C'
color3='#768E8B'
color4='#97A99F'
color5='#B0C7B7'
color6='#CCC4A7'
color7='#eee4c7'
color8='#a69f8b'
color9='#E49E71'
color10='#FEC87C'
color11='#768E8B'
color12='#97A99F'
color13='#B0C7B7'
color14='#CCC4A7'
color15='#eee4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
